"""Add bio and profile-pic path to the users

Revision ID: 18314a098995
Revises: 665200cc52c6
Create Date: 2017-12-14 11:43:05.586301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18314a098995'
down_revision = '665200cc52c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
